name: .NET CI/CD Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # Executa uma vez ao dia à meia-noite (UTC)

jobs:
  build_and_test:
    name: Build and Test on Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Atualize para a versão do .NET que seu projeto está usando

      - name: Restore Dependencies
        run: dotnet restore github4women/github4women.csproj

      - name: Build
        run: dotnet build github4women/github4women.csproj --no-restore

      - name: Run Tests
        run: dotnet test github4women/github4women.csproj --no-build --verbosity normal

  scheduled_task:
    name: Run Scheduled Task
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x' # Atualize para a versão do .NET que seu projeto está usando

      - name: Restore Dependencies
        run: dotnet restore github4women/github4women.csproj

      - name: Build
        run: dotnet build github4women/github4women.csproj --no-restore

      - name: Execute Custom Backup Script
        run: |
          echo "This is a scheduled backup job."
          # Script de backup diário
          diretorio_origem="github4women" # Ajuste o caminho conforme necessário
          diretorio_destino="backups" # Ajuste o caminho conforme necessário
          nome_backup="backup_$(date +%Y-%m-%d_%H-%M-%S).tar.gz"
          mkdir -p "${diretorio_destino}"
          tar -czvf "${diretorio_destino}/${nome_backup}" "${diretorio_origem}"
          if [ $? -eq 0 ]; then
            echo "Backup criado com sucesso em ${diretorio_destino}/${nome_backup}"
          else
            echo "Erro ao criar backup"
            exit 1
          fi

